### PR TITLE
db event outbox (GSI-610)

### PR DESCRIPTION
**Pull request by KerstenBreuer**
```
Implements a wrapper around the existing DaoFactoryProtocol that adds outbox behavior for publishing.
An additional __metadata__ field is added to documents in MongoDB that encodes whether a change has
been published and whether a document was deleted or not.
It is assumed that one topic only contains events related to one resource type stored in one collection.

Bumps version to 2.2.0.
```

### CODE REVIEW

**Review by TheByronHimes — APPROVED** [review]
Very nice, looks like an elegant solution.

**Review by Cito — DISMISSED** [review]
That should work.

We can also consider using dates instead of booleans.

**Review by mephenor — APPROVED** [review]
Not much to add to the previous reviewers.
I like the idea

**Review by Cito — APPROVED** [review]

**Comment by KerstenBreuer** [comment]
Implements a wrapper around the existing DaoFactoryProtocol that adds outbox behavior for publishing.
An additional __metadata__ field is added to documents in MongoDB that encodes whether a change has
been published and whether a document was deleted or not.
It is assumed that one topic only contains events related to one resource type stored in one collection.

Bumps version to 2.2.0.

**Pull request merged**
